version: '3'
services:
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
  app:
    depends_on:
      - db
    image: nemac-drupal-image:latest
    ports:
      - "80:80"
      - "443:443"
    restart: always
    volumes:
      - $PWD:/app
    environment:
      SECRETS_STORE: ''
      ASSET_STORE: ''
      PROJECT_HOSTNAME: '${PROJECT_HOSTNAME}'
      ENABLE_XDEBUG: 'true'
      ENABLE_HTTPS: 'true'
      XDEBUG_REMOTE_HOST: '192.168.99.1'
      ADMIN_EMAIL: 'admin@$PROJECT_HOSTNAME'
      S3_SECRET_ACCESS_KEY: '${S3_SECRET_ACCESS_KEY}'
      S3_ACCESS_KEY_ID: '${S3_ACCESS_KEY_ID}'
volumes:
  db_data:
