version: '3'
services:
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: drupal
      MYSQL_DATABASE: drupal
      MYSQL_USER: drupal
      MYSQL_PASSWORD: drupal
  app:
    depends_on:
      - db
    image: nemac-drupal-image:latest
    ports:
      - "80:80"
      - "443:443"
    restart: always
    volumes:
      - $PWD:/app
    environment:
      SECRETS_STORE: ''
      ASSET_STORE: ''
      S3_SECRET_ACCESS_KEY: '${S3_SECRET_ACCESS_KEY}'
      S3_ACCESS_KEY_ID: '${S3_ACCESS_KEY_ID}'
      PHP_DATE_TIMEZONE: 'America/New_York'
      PHP_MEMORY_LIMIT: '512M'
      PHP_POST_MAX_SIZE: '64M'
      PHP_UPLOAD_MAX_FILESIZE: '64M'
      PHP_MAX_EXECUTION_TIME: '120'
      PROJECT_HOSTNAME: '${PROJECT_HOSTNAME}'
      ENABLE_DEBUGGING: 'true'
      ENABLE_HTTPS: 'false'
      XDEBUG_REMOTE_HOST: '192.168.99.1'
      ADMIN_EMAIL: 'admin@$PROJECT_HOSTNAME'
volumes:
  db_data: