#!/usr/bin/env bash
exec 2>&1

source /etc/container_environment.sh

if [[ "true" == "${ENABLE_DEBUGGING}" ]]; then
export ENABLE_DEBUGGING_BOOL=1
else
export ENABLE_DEBUGGING_BOOL=0
fi

exec httpd -f /etc/httpd/httpd.conf -D FOREGROUND